# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  manna_engine_config = debug
  manna_editor_config = debug

else ifeq ($(config),release)
  manna_engine_config = release
  manna_editor_config = release

else ifeq ($(config),dist)
  manna_engine_config = dist
  manna_editor_config = dist

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := manna_engine manna_editor

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

manna_engine:
ifneq (,$(manna_engine_config))
	@echo "==== Building manna_engine ($(manna_engine_config)) ===="
	@${MAKE} --no-print-directory -C manna_engine -f Makefile config=$(manna_engine_config)
endif

manna_editor: manna_engine
ifneq (,$(manna_editor_config))
	@echo "==== Building manna_editor ($(manna_editor_config)) ===="
	@${MAKE} --no-print-directory -C manna_editor -f Makefile config=$(manna_editor_config)
endif

clean:
	@${MAKE} --no-print-directory -C manna_engine -f Makefile clean
	@${MAKE} --no-print-directory -C manna_editor -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo "  dist"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   manna_engine"
	@echo "   manna_editor"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"